site_name: MCSS Broadcasting Docs
repo_url: https://github.com/mcss-broadcasting/mcss-broadcasting.github.io
edit_uri: edit/master/docs/
theme: readthedocs
theme_dir: 'theme_override'

pages:
  - 'Introduction': 'index.md'
  - 'Cheat Sheets':
    - 'NMS Record/Edit Workstation' : 'cheat-sheets/NMS-Workstations.md'
