site_name: MCSS Broadcasting Docs
repo_url: https://github.com/mcss-broadcasting/mcss-broadcasting.github.io
edit_uri: edit/master/docs/
theme: readthedocs
theme_dir: 'theme_override'

pages:
  - 'Introduction': 'index.md'
  - 'Video How-To':
    - 'Broadcast Video Basics': 'how-to/video/video-basics.md'
    - 'Video Mixer Basics': 'how-to/video/video-mixer-basics.md'
    - 'CasparCG Basics': 'how-to/video/casparcg-basics.md'
  - 'Maintenance Cheat Sheets':
    - 'NMS': 'cheat-sheets/NMS-Maintenance.md'
